spring:
  application:
    name: release-notes-generator
  main:
    web-application-type: none

logging:
  level:
    root: info
    sun.net.www.protocol.http.HttpURLConnection: info
    com.ct.rng: info

releasenotes:
  regexExpression: '^\d*[.]\d*[.]\d*[.]RELEASE$'
