spring:
  application:
    name: release-notes-generator
  main:
    web-application-type: none

logging:
  level:
    root: debug
    sun.net.www.protocol.http.HttpURLConnection: debug
    com.ct.rng: info

releasenotes:
  regexExpression: '^\\d*[.]\\d*[.]\\d*[.]RELEASE$'
